baseURL: "https://worldfishcenter.github.io/rappseq/"
languageCode: "en-us"
title: "AquaPath"
theme: "rappseq"
params:
  copyrightHolder: WorldFish

menu: 
  main:
    - name: Pathogens
      weight: 2
      url: "/pathogens/"
    - name: Identification
      weight: 1
    - name: How does it work?
      url: /how-does-it-work/
      weight: 2
      parent: "Identification"
    - name: Our classifiers
      url: /classifiers/
      parent: "Identification"
    - name: Identification tool
      url: /identify/
      parent: "Identification"
      weight: 1
    - name: Management
      url: /disease-management/
  footer:
    - name: Privacy policy
      url: /privacy-policy/
    - name: Terms of service
      url: /terms-of-service/
    
    