baseURL: "https://worldfishcenter.github.io/rappseq/"
languageCode: "en-us"
title: "AquaPath"
theme: "rappseq"
params:
  copyrightHolder: WorldFish
  acknowledgements: AquaPath is partially funded by the CGIAR Research Programs on Fish Agri-Food Systems (FISH) led by WorldFish, the CGIAR Antimicrobial Resistance Hub on AMR related activities and from the CGIAR Platform for Big Data in Agriculture as part of the 2019 Inspire Challenge prize.
  footer_intro: AquaPath is a joint digital initiative in collaboration with the University of Queensland and Wilderlab. 

menu: 
  main:
 #   - name: Pathogens
 #     weight: 2
 #     url: "/pathogens/"
    - name: Identification
      weight: 1
    - name: How does it work?
      url: /how-does-it-work/
      weight: 2
      parent: "Identification"
    - name: Our classifiers
      url: /classifiers/
      parent: "Identification"
    - name: Identification tool
      url: /identify/
      parent: "Identification"
      weight: 1
    - name: Management
      url: /disease-management/
  footer:
    - name: Privacy policy
      url: /privacy-policy/
    - name: Terms of service
      url: /terms-of-service/
    
    