baseURL: "https://worldfishcenter.github.io/rappseq/"
languageCode: "en-us"
title: "AquaPath"
theme: "rappseq"
params:
  copyrightHolder: WorldFish

menu: 
  main:
    - name: Pathogens
      weight: 2
      url: "/pathogens/"
    - name: Identification
      weight: 1
    - name: Documentation
      url: /identify/documentation
      parent: "Identification"
    - name: Identification tool
      url: /identify/
      parent: "Identification"
      weight: 1
      pill: v0.0.1
  footer:
    - name: Privacy policy
      url: /privacy-policy/
    - name: Terms of service
      url: /terms-of-service/
    
    