
on:
  push:
    paths: 
      - 'site/*'
      - '.github/workflows/build-hugo-site.yml'
    branches:
      - main

jobs:
  build-site:
    name: Build hugo site
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.86.0'
          extended: true

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: ls site/themes/rappseq/assets
      - run: ls site/themes/rappseq/assets/front-v3.3/
      - name: Install node dependencies
        run: npm install site/themes/rappseq/assets/front-v3.3/
      
      - name: Build site
        run: "cd site && hugo --minify"
      
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/public