
on:
  push:
    paths:
      - 'api/*'
      - '.github/workflows/deploy-api.yml'
    branches:
      - main

name: Build and deploy the Rappseq API

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: rappseq-api
  REGION: asia-east1
  CONTAINER_REGISTRY: asia.gcr.io

jobs:
  deploy:
    name: Deploy identification API
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true  # Set to true to authenticate the Cloud Run action

    - name: Retrieve kmer classifier databases
      run: |-
        gsutil cp -r gs://rappseq-data-1/classifiers/GBS/210524.db api/data/classifiers/GBS/210524.db
        gsutil cp -r gs://rappseq-data-1/classifiers/GBS/210524_sero.db api/data/classifiers/GBS/210524_sero.db
        gsutil cp -r gs://rappseq-data-1/classifiers/GBS/210607.db api/data/classifiers/GBS/210607.db

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and push API container
      run: |-
        docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} api/
        docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0.5.0
      with:
        service: ${{ env.SERVICE }}
        image: ${{ env.CONTAINER_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
        region: ${{ env.REGION }}
        flags: "--cpu=1 --memory=1Gi --concurrency=10"

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
