on:
  push:
    branches:
      - main

jobs:
  deploy-shinyapps-io:
    name: Deploy on shinyapps.io
    runs-on: macos-10.15
    env:
      SHINYAPPS_TOKEN: ${{secrets.SHINYAPPS_TOKEN}}
      SHINYAPPS_SECRET: ${{secrets.SHINYAPPS_SECRET}}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Retrieve kmer classifier database
        run: gsutil cp -r gs://rappseq-data-1/classifiers data

      - name: Retrieve reference sequences
        run: gsutil -m cp -r gs://rappseq-data-1/refseqs data

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.5'

      - name: Install R-package dependencies
        run: install.packages(c('shiny', 'rsconnect', 'insect', 'RSQLite', 'DT', 'waiter', 'shinyWidgets'))
        shell: Rscript {0}

      - name: Set shinyapps.io account info
        run: Rscript -e "rsconnect::setAccountInfo(name='worldfish', token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))"

      - name: Push to shinyapps.io
        run: Rscript -e "rsconnect::deployApp(appName = 'rappseq2', appTitle = 'rappseq2')"
